BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `pikachus` (
	`id_pika`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name_pika`	TEXT NOT NULL UNIQUE,
	`image_pika`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `memes` (
	`id_meme`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name_meme`	TEXT NOT NULL UNIQUE,
	`link_meme`	INTEGER NOT NULL
);
COMMIT;
