BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `pikachus` (
	`id_pika`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name_pika`	TEXT NOT NULL UNIQUE,
	`image_pika`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `memes` (
	`id_meme`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name_meme`	TEXT NOT NULL UNIQUE,
	`link_meme`	TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `reminders` (
	`id_reminder`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`uuid_reminder` TEXT NOT NULL UNIQUE,
	`date_reminder` TIMESTAMP NO NULL,
	`author_reminder`	INTEGER NOT NULL,
	`text_reminder`	TEXT NOT NULL
);
COMMIT;
