DATABASE_NAME = "botchevik.db"
USER_AGENT = "Botchevik/1.0"
MAX_NOT_ASSUMING_SECONDS = 20
MIN_NOT_ASSUMING_SECONDS = 1
MAX_NOT_ASSUMING_NEXT_SECONDS = 20
MIN_INSANITY_LEVEL = 0
MAX_INSANITY_LEVEL = 7
MEME_BASE_VOLUME = 0.75
