# Database
DATABASE_NAME = "botchevik.db"

# User agent
USER_AGENT = "Botchevik/1.0"

# Messages lifetime
ERROR_MESSAGE_LIFETIME = 60
HELP_MESSAGE_LIFETIME = 30

# Not_assuming module
MAX_NOT_ASSUMING_SECONDS = 20
MIN_NOT_ASSUMING_SECONDS = 1
MAX_NOT_ASSUMING_NEXT_SECONDS = 20

# Youtubedlsource util
MEME_BASE_VOLUME = 0.75
FFMPEG_EXECUTE_PATH = "ffmpeg"

# flood module
FLOOD_COOLDOWN_TIME = 60
NUMBER_OF_SUPER_MESSAGE = 5
MIN_NUMBER_OF_MESSAGE = 2
MAX_NUMBER_OF_MESSAGE = 6
MIN_NUMBER_OF_PARTS = 1
MAX_NUMBER_OF_PARTS = 6
MIN_QUESTION_MARKS_PER_PARTS = 4
MAX_QUESTION_MARKS_PER_PARTS = 16
RANDOM_WTF_CHANCE = 0.2
RANDOM_SPACE_CHANCE = 0.05
WAITING_TIME_BEFORE_DELETION = 5

# Lewd things
# nhentai disabled their API, if it come back, just switch to on :)
# False = Web scrapping
# True  = Call to the api
LEWD_USE_API=False